version: "3"
services:
  redis:
    image: redis
  server:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: bash -c "python manage.py migrate core && python manage.py runserver 0:8000"
    depends_on:
      - redis
      - worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    ports:
      - 8000:8000
    volumes:
      - .:/code
  beat:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: bash -c "python manage.py migrate core && celery -A tcchallenge beat -l INFO"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - .:/code
  worker:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: bash -c "python manage.py migrate core && celery -A tcchallenge worker -l INFO"
    depends_on:
      - beat
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - .:/code
