# Generated by Django 3.1.6 on 2021-02-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scraper_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraper',
            options={'verbose_name': 'Scraper', 'verbose_name_plural': 'Scrapers'},
        ),
        migrations.RenameField(
            model_name='assetdata',
            old_name='retunrs_24h',
            new_name='returns_24h',
        ),
        migrations.RenameField(
            model_name='assetdata',
            old_name='retunrs_ytd',
            new_name='returns_ytd',
        ),
    ]
